package cn.pup.erp.iteration.entity;

import java.util.Date;

/**
 * The Class is generated by Mybatis Generator.
 * The fields are correspond to the database column tbl_feedback with uppercase-camel rules.
 */
public class Feedback {

    private Integer feedbackId;

    private String module;

    private String category;

    private String type;

    private String feedbackTitle;

    private String feedbackContent;

    private Boolean isHasAttachment;

    private String feedbackStatus;

    private String reply;

    private String replier;

    private Date gmtReply;

    private Boolean isValid;

    private String creator;

    private Date gmtCreate;

    private String modifier;

    private Date gmtModified;

    public Integer getFeedbackId() {
        return feedbackId;
    }

    public void setFeedbackId(Integer feedbackId) {
        this.feedbackId = feedbackId;
    }

    public String getModule() {
        return module;
    }

    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    public String getFeedbackTitle() {
        return feedbackTitle;
    }

    public void setFeedbackTitle(String feedbackTitle) {
        this.feedbackTitle = feedbackTitle == null ? null : feedbackTitle.trim();
    }

    public String getFeedbackContent() {
        return feedbackContent;
    }

    public void setFeedbackContent(String feedbackContent) {
        this.feedbackContent = feedbackContent == null ? null : feedbackContent.trim();
    }

    public Boolean getIsHasAttachment() {
        return isHasAttachment;
    }

    public void setIsHasAttachment(Boolean isHasAttachment) {
        this.isHasAttachment = isHasAttachment;
    }

    public String getFeedbackStatus() {
        return feedbackStatus;
    }

    public void setFeedbackStatus(String feedbackStatus) {
        this.feedbackStatus = feedbackStatus == null ? null : feedbackStatus.trim();
    }

    public String getReply() {
        return reply;
    }

    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    public String getReplier() {
        return replier;
    }

    public void setReplier(String replier) {
        this.replier = replier == null ? null : replier.trim();
    }

    public Date getGmtReply() {
        return gmtReply;
    }

    public void setGmtReply(Date gmtReply) {
        this.gmtReply = gmtReply;
    }

    public Boolean getIsValid() {
        return isValid;
    }

    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public String getModifier() {
        return modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    @Override
    public String toString() {
        return "Feedback{" +
                "feedbackId=" + feedbackId +
                ", module='" + module + '\'' +
                ", category='" + category + '\'' +
                ", type='" + type + '\'' +
                ", feedbackTitle='" + feedbackTitle + '\'' +
                ", feedbackContent='" + feedbackContent + '\'' +
                ", isHasAttachment=" + isHasAttachment +
                ", feedbackStatus='" + feedbackStatus + '\'' +
                ", reply='" + reply + '\'' +
                ", replier='" + replier + '\'' +
                ", gmtReply=" + gmtReply +
                ", isValid=" + isValid +
                ", creator='" + creator + '\'' +
                ", gmtCreate=" + gmtCreate +
                ", modifier='" + modifier + '\'' +
                ", gmtModified=" + gmtModified +
                '}';
    }
}