package cn.pup.erp.iteration.entity;

import java.util.Date;

/**
 * This file was generated by MyBatis Generator corresponded to the database tbl_dictionary.
 *
 * @author hh
 */
public class Item {

    private Integer itemId;

    private String itemName;

    private Integer parentId;

    private Integer categoryLevel;

    private Integer orderNumber;

    private Boolean isHadChild;

    private Boolean isValid;

    private String creator;

    private Date gmtCreate;

    private String modifier;

    private Date gmtModified;

    private String comment;

    public Integer getItemId() {
        return itemId;
    }

    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public Integer getCategoryLevel() {
        return categoryLevel;
    }

    public void setCategoryLevel(Integer categoryLevel) {
        this.categoryLevel = categoryLevel;
    }

    public Integer getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    public Boolean getIsHadChild() {
        return isHadChild;
    }

    public void setIsHadChild(Boolean isHadChild) {
        this.isHadChild = isHadChild;
    }

    public Boolean getIsValid() {
        return isValid;
    }

    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public String getModifier() {
        return modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    @Override
    public String toString() {
        return "Item{" +
                "itemId=" + itemId +
                ", itemName='" + itemName + '\'' +
                ", parentId=" + parentId +
                ", categoryLevel=" + categoryLevel +
                ", orderNumber=" + orderNumber +
                ", isHadChild=" + isHadChild +
                ", isValid=" + isValid +
                ", creator='" + creator + '\'' +
                ", gmtCreate=" + gmtCreate +
                ", modifier='" + modifier + '\'' +
                ", gmtModified=" + gmtModified +
                ", comment='" + comment + '\'' +
                '}';
    }
}